### ISSUE TITLE
Define the performance attribute for workers

### ISSUE THREAD

**Issue by foolip** [w3c/hr-time#10]
Separate issue from https://github.com/w3c/hr-time/issues/9 since this may actually require discussion.

FWIW, it's already exposed in workers in at least Blink and Gecko.

In Blink it's a bit weird, with a separate `[NoInterfaceObject] interface WorkerPerformance` that looks a lot, but not exactly, like the `Performance` interface.

Following Gecko would probably make more sense, they just use `[Exposed=(Window,Worker)]` or `[Exposed=Window]` as makes sense.

CC @bzbarsky

**Comment by bzbarsky** [comment]
Yeah, the WorkerPeformance hack is how things used to be done on workers before `Exposed` existed.

**Comment by igrigorik** [comment]
@foolip that's how it's specced in latest draft: https://w3c.github.io/hr-time/#the-performance-interface. Anything else we're missing?

**Comment by foolip** [comment]
What's missing is the `WorkerGlobalScope.performance` attribute, i.e. something like
```WebIDL
partial interface WorkerGlobalScope {
    [SameObject] readonly attribute Performance performance;
};
```

**Comment by foolip** [comment]
The `Exposed` question isn't something that this spec would have to deal with, but it looks like both Blink and Gecko limits `timing`, `navigation` and some other things to just `Window`.

**Comment by igrigorik** [comment]
> What's missing is the WorkerGlobalScope.performance attribute, i.e. something like

I believe that's covered within Performance Timeline: http://w3c.github.io/performance-timeline/#attributes-1

>  it looks like both Blink and Gecko limits timing, navigation and some other things to just Window.

That's correct and as intended. Within (service)worker everything looks like a resource request.. there are no "navigations", hence no need to exposing timing or navigation (which belong to NT1).

**Comment by foolip** [comment]
Oh, it never struck me to look in any other spec than the one that defines the `Performance` interface for that... should I close this and https://github.com/w3c/hr-time/issues/9 and instead file an issue to move that, or is it in Performance Timeline for a reason?

As for `Exposed` on `timing` and `navigation`, let's discuss that in https://github.com/w3c/navigation-timing/issues/22

**Comment by igrigorik** [comment]
Background on why we (recently) moved Performance interface into HR-Time: https://lists.w3.org/Archives/Public/public-web-perf/2015Jun/0073.html -- fwiw, I still think that the two are coupled at the hip and its not unreasonable to just merge them; perhaps that would resolve some of the confusion. 

That said, on a more practical note: yes, I think we should move that definition into HR-time, which would also resolve #9. However, before I do that, I'd like to get a sanity check from @plehegar and @toddreifsteck :)

**Comment by toddreifsteck** [comment]
@igrigorik Agreed on both the quick, practical note AND refactoring to merge performance-timeline and hr-time into a single "base spec" for performance .

**Comment by igrigorik** [comment]
What we have in Performance Timeline today:

```
<dl class='idl' title='[NoInterfaceObject, Exposed=(Window,Worker)] interface GlobalPerformance'>
<dt>[Replaceable] readonly attribute Performance performance</dt>
<dd>This attribute allows access to performance related attributes and methods.</dd>
</dl>

<pre class='idl'>
Window implements GlobalPerformance;
WorkerGlobalScope implements GlobalPerformance;
</pre>
```

Are we OK to simplify this to (and move it to HR-Time):

```
<dl class='idl' title='[NoInterfaceObject, Exposed=(Window,Worker)] interface GlobalPerformance'>
<dt>[Replaceable] readonly attribute Performance performance</dt>
<dd>This attribute allows access to performance related attributes and methods.</dd>
</dl>
```

@bzbarsky @foolip sanity check?

**Comment by bzbarsky** [comment]
@igrigorik Is the simplification the removal of the two `implements` statements?  I don't think you can remove them.

**Comment by foolip** [comment]
Right, the `implements` bits are needed.

**Comment by igrigorik** [comment]
Thanks guys. Moved definition, see: https://github.com/w3c/performance-timeline/commit/0d05bc4021e548454de31f1a9e299c4e0143e990 +  54a416e. Feel free to reopen if there is anything else missing.

**Comment by foolip** [comment]
Looks great, thanks Ilya!
