### ISSUE TITLE
Define `timeOrigin` in the HTML spec

### ISSUE THREAD

**Issue by noamr** [w3c/hr-time#131]
Instead of saying what `timeOrigin` means, set it explicitly in the HTML spec at the right moments.

**Comment by yoavweiss** [comment]
Should we hang it off of the global object? environment settings object?

**Comment by noamr** [comment]
I'm working on a patch.
I believe it should be associated with a document and with a WorkerGlobalScope. Otherwise it would get fudged in BFCache (which is unspecified behavior today)

**Comment by noamr** [comment]
... problem is that during navigation time recording there is no document yet, so this would take some delicate handling

**Comment by noamr** [comment]
> It should be `Window` or `WorkerGlobalScope`, no?

See the [html PR](https://github.com/whatwg/html/pull/7339). It's in the environment settings object, which is where the "virtual" things that can go to either a window or a worker but in a different way are defined.
