### ISSUE TITLE
Please add a giant red warning to http://www.w3.org/TR/hr-time/

### ISSUE THREAD

**Issue by domenic** [w3c/hr-time#15]
http://www.w3.org/TR/hr-time/ is obsolete and contributing to confusion, see e.g. the IntersectionObserver repo. Implementers would benefit greatly from a giant red warning on it directing them to https://w3c.github.io/hr-time/.

For an example of precedent on these see e.g. http://www.w3.org/TR/url/.

@sideshowbarker might be able to help here.

**Comment by sideshowbarker** [comment]
I’ll follow up with @plh about this (he manages this group), and with @siusin (who I think is helping out plh with it some these days).

**Comment by igrigorik** [comment]
We should probably publish a new draft as well.. FWIW, I'd love to see https://github.com/w3c/hr-time/pull/14 resolved first though, but that requires some work in HTML spec too.

**Comment by plehegar** [comment]
hr-time-2 draft is up-to-date but no one implements as-is yet, so we can't simply replace the Rec with the new version. If we subset it, we might be able to push something forward but we would have to leave translateTime out since it lacks implementation. We could indeed update the Rec with a pointer to http://www.w3.org/TR/hr-time-2/.

**Comment by igrigorik** [comment]
+1 for adding a pointer.

**Comment by domenic** [comment]
Please https://w3c.github.io/hr-time/ instead of http://www.w3.org/TR/hr-time-2/. We don't need more insecure links in this ecosystem.

**Comment by plehegar** [comment]
Once #14 lands, I'll address this one by doing our "Great Renaming of WebPerf specs" plan and add a warning.

**Comment by igrigorik** [comment]
I believe this should be unblocked now?

**Comment by plehegar** [comment]
prepared
 http://www.w3.org/2015/11/hr-time-1.html

**Comment by igrigorik** [comment]
:+1:

**Comment by plehegar** [comment]
Deployed at http://www.w3.org/TR/2012/REC-hr-time-20121217/ and http://www.w3.org/TR/hr-time-1/

http://www.w3.org/TR/hr-time/ now points to HRT2 and we'll keep pointing it to the latest version.
