### ISSUE TITLE
Better ids for the two "unsafe current time"s

### ISSUE THREAD

**Issue by jyasskin** [w3c/hr-time#156]
Right now, the id for the wall clock's unsafe current time is https://w3c.github.io/hr-time/#dfn-unsafe-current-time-0, and the id for the monotonic clock's unsafe current time is https://w3c.github.io/hr-time/#dfn-unsafe-current-time-1. They're not using the `<dfn>`'s `for` value as part of the id. If we ever re-order the text, I believe the link targets will stay in document order instead of following the semantics, which isn't great. We should provide explicit `id=` attributes to avoid that.

**Comment by yoavweiss** [comment]
^^ @noamr
