### ISSUE TITLE
Need a changelist without translateTime so we can publish 

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/hr-time#16]

**Comment by toddreifsteck** [comment]
Update title

**Comment by igrigorik** [comment]
I recall @plehegar saying that we can just mark translateTime as "at risk", without removing it?

**Comment by plehegar** [comment]
Yes, for our move to CR, but I'll still come up with a list of changes anyway. Note that I don't plan to remove translateTime for the Editors' draft in any case. It will only be remove in the branch.
