### ISSUE TITLE
"safe" time in milliseconds since epoch without settings object

### ISSUE THREAD

**Issue by annevk** [w3c/hr-time#165]
I need this concept in Declarative Web Push, but I'm having a hard time figuring out the necessary wording.

**Comment by yoavweiss** [comment]
If I understand what you need correctly, I think we can define it in a similar way to the [current wall time](https://w3c.github.io/hr-time/#ref-for-dfn-coarsen-time-3) definition, only with the monotonic clock. Would that work?

**Comment by annevk** [comment]
Well, "current wall time" requires a settings object.

I guess maybe what I need is this:

1. Let unsafeMonotonicTime be the [monotonic clock](https://w3c.github.io/hr-time/#dfn-monotonic-clock)'s [unsafe current time](https://w3c.github.io/hr-time/#monotonic-clock-unsafe-current-time).
2. Return the result of calling [coarsen time](https://w3c.github.io/hr-time/#dfn-coarsen-time) with unsafeMonotonicTime.

(Because coarsen time takes an optional boolean as second argument that defaults to safe.)

Although maybe the monotonic clock is wrong as it never decreases? I don't know enough about whether I need the wall clock or the monotonic clock. We used to write "time in milliseconds since epoch" but I guess that was never precise enough?

**Comment by yoavweiss** [comment]
Oh, I think I see the source of confusion here.
We seem to have two different "current wall time" definitions.

A [generic one](https://w3c.github.io/hr-time/#dfn-current-wall-time) defined as the "result of calling [coarsen time](https://w3c.github.io/hr-time/#dfn-coarsen-time) with the [wall clock](https://w3c.github.io/hr-time/#dfn-wall-clock)'s [unsafe current time](https://w3c.github.io/hr-time/#wall-clock-unsafe-current-time).", which is what I think you want for "time in milliseconds since epoch".

The [other one](https://w3c.github.io/hr-time/#dfn-eso-current-wall-time), is attached to a settings object and relies on it.

We should probably rename one of them.

**Comment by annevk** [comment]
What's the difference between the wall time and monotonic clock?

I need to end up with a EpochTimeStamp here, similar to how https://notifications.spec.whatwg.org/#create-a-notification-with-a-settings-object creates one (_fallbackTimestamp_) I suspect, except I don't have an environment settings object available here.

Any help with this would be appreciated as this is blocking Declarative Web Push work.

**Comment by yoavweiss** [comment]
> What's the difference between the wall time and monotonic clock?

"wall clock" is defined as "as close as possible to a user's notion of time". In practice that means that it can be adjusted both up and down (e.g. if the computer hibernates or NTP/user adjust its clock)

The monotonic clock can't be adjusted and keeps ticking forward at a steady pace when the computer/browser is working. That's better for performance measurements, but AFAICT not what you want necessarily.



> Any help with this would be appreciated as this is blocking Declarative Web Push work.

I'll put together a PR to try and unblock you. Apologies for the delay..

**Comment by yoavweiss** [comment]
https://github.com/w3c/hr-time/pull/167 defines a "current coarsen wall time" which I think is the concept you need

**Comment by yoavweiss** [comment]
@annevk - feel free to reopen if [current coarsened wall time](https://w3c.github.io/hr-time/#dfn-current-wall-time) doesn't address your needs.

**Comment by annevk** [comment]
That looks excellent, thank you!
