### ISSUE TITLE
Make translateTime work with Client objects

### ISSUE THREAD

**Issue by annevk** [w3c/hr-time#23]
Currently `translateTime` cannot be used well in service workers which has `Client` objects to represent other globals.

**Comment by igrigorik** [comment]
Should `translateTime` be extended to support [Client](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#client-interface) as its second param? Any gotchas associated with this route?

**Comment by annevk** [comment]
Yeah, I think that is what @sicking had in mind (I raised this issue and the other one based on a Mozilla dev.platform thread).

**Comment by igrigorik** [comment]
Let's merge this into #22, same underlying issue.
