### ISSUE TITLE
Warning against differentiation

### ISSUE THREAD

**Issue by plehegar** [w3c/hr-time#24]
[[
Sometimes identification may not be possible to achieve. But it can still
allow "differentiation" between several users. Maybe it's worth to enhance
the Considerations and add something along "identify as particular user, or
differentiate between many users"?
]]
https://lists.w3.org/Archives/Public/public-privacy/2016JanMar/0006.html
From @lknik

**Comment by igrigorik** [comment]
_"Cache attacks and statistical fingerprinting is a privacy and security concern where a malicious web site may use high resolution timing data of various browser or application-initiated operations to differentiate between sub-populations of users, and in some cases identify a particular user - see [CACHE-ATTACKS]"_

Would that work?

**Comment by yoavweiss** [comment]
I'd love to hear clarifications of what "sub-populations of users" mean. Are we talking about identifying browser implementations (vs. the advertised UA string)? Identifying device types?

**Comment by igrigorik** [comment]
Anyone one of the above? I believe the point here is to simply highlight that timing data can leak information about the system, and depending on variety of factors of how it's collected, etc, that may allow you to identify a subset of users, and in some cases maybe even a particular individual.

I'm happy to go back to "differentiate between many users" if that's clearer.

**Comment by eliperelman** [comment]
+1 to @igrigorik language.

**Comment by igrigorik** [comment]
@plehegar suggested "subset". I'll update and merge.

**Comment by yoavweiss** [comment]
OK, language works for me

**Comment by plehegar** [comment]
:+1:
