### ISSUE TITLE
Move boilerplate URLs to HTTPS

### ISSUE THREAD

**Issue by tripu** [w3c/hr-time#33]
Last attempt to publish automatically [failed](https://lists.w3.org/Archives/Public/public-tr-notifications/2016Oct/0001.html) because:

* The [stated URL for the WG](https://github.com/w3c/hr-time/blob/gh-pages/index.html#L34) does not match [the one on our DB](https://www.w3.org/groups/w3cgroups/45211) (HTTP vs HTTPS).
* [Public list of patent disclosures](https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/hr-time/index.html?specStatus=WD;shortName=hr-time-2;useExperimentalStyles=false#h-sotd) is also missing HTTPS.

ping @plehegar, @igrigorik.

**Comment by igrigorik** [comment]
Slight tangent, but... @toddreifsteck @plehegar how do we proceed with L2 vs L3? 

- We have https://github.com/w3c/hr-time/tree/hr-time-2-CR that Philippe created while back. Should we merge https://github.com/w3c/hr-time/commit/5b33e0ecb3a9c0fa4f01b8b086b157354474fec9 into that branch and use that as our branch for all V2 related changes?
- I also created https://github.com/w3c/hr-time/tree/V2 earlier.. but it doesn't make sense to have both Phillippe's branch above and this one. Should I delete V2?
- Last but not least.. I'm assuming that moving forward we'll treat gh-pages ("master") as Level 3. 

Any objections? 

p.s. I'll fix the HTTPS urls.. just need to figure out what/where I should be pushing.

**Comment by plehegar** [comment]
I fixed the links (thanks @tripu for the ping). 
hr-time-2-CR should be deleted. I think it was created at a time when translateTime was still on the table and it's no longer in the main branch. So, unless I missed a new functionality in the spec, we could push the current hr-time-2 to CR/PR/REC within 3 months imho. If we don't have enough tests, someone should open an issue on hr-time, list what they think is missing. We might get someone else to pick it up from there and write the tests.
Btw, the spec is always automatically published from gh-pages, so fix stuff on that branch if automatic publishing fails.

**Comment by igrigorik** [comment]
> hr-time-2-CR should be deleted. I think it was created at a time when translateTime was still on the table and it's no longer in the main branch.

Done.

> So, unless I missed a new functionality in the spec, we could push the current hr-time-2 to CR/PR/REC within 3 months imho. If we don't have enough tests, someone should open an issue on hr-time, list what they think is missing. We might get someone else to pick it up from there and write the tests.

Yep, let's discuss this on this weeks call.

Closing this issue, thanks for fixing the links Philippe!
