### ISSUE TITLE
Transition Level 2 to CR

### ISSUE THREAD

**Issue by igrigorik** [w3c/hr-time#34]
Preview: https://cdn.rawgit.com/w3c/hr-time/v2/index.html
- [ ] **Web platform tests**
  - TODO: https://github.com/w3c/hr-time/issues/32
  - [x] verify implementation in Worker's - see https://github.com/w3c/hr-time/issues/34#issuecomment-255873659.
- [x] **Known / outstanding spec issues**
  - none
- [x] **Privacy and security**
  - http://w3c.github.io/hr-time/#privacy-security
- [x] **Implementations**
  - Chrome: [M46+](https://www.chromestatus.com/feature/6337483654561792)
  - Firefox: [M45+](https://groups.google.com/forum/#!topic/mozilla.dev.platform/PBiil3ItyeY/discussion)
  - Edge: [14.14393](https://blogs.windows.com/msedgedev/2016/02/03/2016-platform-priorities/)
  - Safari: no public signals (not in iOS 10.1)
- [x] **Update acknowledgements**

**Comment by igrigorik** [comment]
Pushed a small update to the Ack's section of L2. With that in place, as far as the document itself is concerned, I believe it's ready to go. The only remaining bits are the test TODO's..

> TODO: test and verify implementation in Worker's

@plehegar I see a test [checked-in for this](https://github.com/w3c/web-platform-tests/blob/master/hr-time/basic.worker.js), but I don't see from where it is called (if, at all) in the test harness. Are we missing the companion HTML file?

> TODO: add prompt to unload test

@plehegar @toddreifsteck @siusin would one of you be willing to take a run at this one?

**Comment by plehegar** [comment]
Re worker, one has to call it with an .html extension to trigger the server transformation:
 http://w3c-test.org/hr-time/basic.worker.html
(works on Chrome, FF, Edge)

I assigned #32 to me.

**Comment by plehegar** [comment]
Btw, /TR/hr-time-2/ got republished with the latest hr-time-2 bits:
 https://lists.w3.org/Archives/Public/public-tr-notifications/2016Oct/0084.html
Once we switched to CR, the publication will have to be manual.

To publish hr-time-3, the Group needs to give the ok for a first Public Working Draft. After we can have the automatic publication of hr-time-3 triggered.

**Comment by plehegar** [comment]
Fyi, I filed https://github.com/w3c/wpt-tools/issues/129 regarding the worker test

**Comment by plehegar** [comment]
(/TR/hr-time-2 got fixed btw)

**Comment by plehegar** [comment]
btw, we have a dependency on service-wokers in hr-time-2 but I think it should only really be on Workers.  opinions?

**Comment by igrigorik** [comment]
> (/TR/hr-time-2 got fixed btw)

Yay, thank you!

> btw, we have a dependency on service-wokers in hr-time-2 but I think it should only really be on Workers. opinions?

We do? I can't find it on https://www.w3.org/TR/hr-time-2/?

**Comment by plehegar** [comment]
I removed but from there since I thought it shouldn't be there. But lok at the editors draft:
https://w3c.github.io/hr-time/
Happy to send a PR if you'd like.

**Comment by igrigorik** [comment]
Oh, I see.. Yeah, that seems unnecessary, we can remove that from L3. Got confused since we're talking about L2 here :)

**Comment by plehegar** [comment]
Made one minor clarification in the status (a1fdd19). On track for November 1 publication.

**Comment by plehegar** [comment]
HRT2 is now a CR and HRT3 is now a FPWD.

**Comment by igrigorik** [comment]
\o/ ... any objections to closing this bug then? We'll track #32 separately.

**Comment by toddreifsteck** [comment]
LGTM
