### ISSUE TITLE
timeOrigin prose doesn't make sense

### ISSUE THREAD

**Issue by bzbarsky** [w3c/hr-time#36]
The IDL says:

```
readonly attribute DOMHighResTimeStamp timeOrigin;
```

and the prose says:

> The timeOrigin attribute MUST return a DOMHighResTimeStamp representing the high resolution time of the time origin timestamp of the global object.

where "time origin timestamp" is defined as:

> - If time origin is undefined, return undefined. 
> - Otherwise, the sum of the high resolution Unix time at which the global monotonic clock is zero and the time value of the global monotonic clock at which the time origin is zero. 

OK, so if time origin is undefined... what does the `.timeOrigin` attribute return?  `undefined` is not a valid `DOMHighResTimeStamp` value.

**Comment by bzbarsky** [comment]
Or is the point that Window and WorkerGlobalScope always define time origin and hence "time origin timestamp" is never undefined in those globals?  But then why are we defining the "time origin timestamp" in more generality than it makes sense to define it?

**Comment by igrigorik** [comment]
@bzbarsky that fell out of our [definition of 'time origin'](https://w3c.github.io/hr-time/#time-origin-1) which itself provides the case where it can be undefined outside of cases we explicitly enumerated in the spec -- added in https://github.com/w3c/hr-time/commit/4093e7f8df4eb97ca14a4642bdfeb02a5a6724d6. 

> undefined is not a valid DOMHighResTimeStamp value.

I agree that this is confusing. Open to suggestions..

**Comment by bzbarsky** [comment]
Well, one option is to not make it sounds like that case can happen.  Right now there are two bits that both attempt to define what the "timeOrigin" attribute should return, in some weird interaction:

1. The text at https://w3c.github.io/hr-time/#dom-performance-timeorigin
2. The text at https://w3c.github.io/hr-time/#time-origin-timestamp

One plausible way to spec this more clearly is as follows:

> To _get the time origin timestamp_ for a global object _G_, perform the following steps:
> 1. Assert: _G_ has a defined time origin.
> 2. Let _t1_ be the DOMHighResTimeStamp representing the high resolution Unix time at which the global monotonic clock is zero.  Note: _t1_ does not depend on _G_.
> 3. Let _t2_ be the DOMHighResTimeStamp representing the time value of the global monotonic clock at _G_'s time origin.
> 4. Return _t1_ + _t2_

and then specify that getting `.timeOrigin` gets the time origin timestamp for "the global object" (need to actually specify which one, too!).

This avoids phrases like "at which time origin is zero" which don't make sense, because the time origin is a timestamp, not a number; in general only differences between two timestamps can be expressed as numbers not timestamps themselves.  It's unfortunate that we have a `DOMHighResTimeStamp` type which actually represents a difference of timestamps, not a timestamp...

**Comment by igrigorik** [comment]
@bzbarsky thanks. WIP: https://github.com/w3c/hr-time/pull/37 - how does that look?
