### ISSUE TITLE
Update worker reference

### ISSUE THREAD

**Issue by igrigorik** [w3c/hr-time#46]
From https://github.com/w3c/hr-time/pull/45#issuecomment-295360008:

> The references to the W3C unmaintained fork of workers rather than the WHATWG HTML Standard will end up confusing implementers. I personally wouldn't accept that.

**Comment by siusin** [comment]
The WebPlat WG have a new editor working on the WebWorkers spec, he said he would push an update very soon... so I suggest we keep it as it is and move to CR. If there is no improvement in the CR period (i.e. four weeks), we will need to consider the other alternatives, f.ex., adding a note and pointing to the WHATWG version as we did for URL.

Would you be fine with that? @annevk

**Comment by siusin** [comment]
There isn't any progress on the W3C WebWorker spec yet... we'll use the best reference we can find at the moment, ie. the WHATWG version.

**Comment by igrigorik** [comment]
👍
