### ISSUE TITLE
Security Review

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/hr-time#60]
Philippe mentioned that there is interest in having HR-Time 2 undergo another security review before sending it to next phase in process. We should do that!

**Comment by igrigorik** [comment]
Is there a particular reason, or question that needs to be addressed?

**Comment by plehegar** [comment]
nope, nothing specific. Just wanted to make sure we did a loop since we didn't do such review for quite some time.

**Comment by yoavweiss** [comment]
/cc @mikewest @arturjanc
Could you kind folks recommend who would be a good person/group to give the spec language a review before we more it forward?

**Comment by plehegar** [comment]
Review requested:
 https://lists.w3.org/Archives/Public/public-web-security/2018Dec/0000.html

**Comment by yoavweiss** [comment]
Thanks @plehegar!

**Comment by yoavweiss** [comment]
The review seems to have passed with no particular concerns. Closing.
