### ISSUE TITLE
Find better sources to quote than Wikipedia

### ISSUE THREAD

**Issue by yoavweiss** [w3c/hr-time#62]
For both "unix-time" and "clock drift", we're citing Wikipedia, which seems shaky.

We should find better places for those definitions.
For "time", there's a definition in [ECMA-262](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-time-values-and-time-range) which we could point to or borrow.
For "clock drift", we may need to define our own

**Comment by igrigorik** [comment]
Could we improve the definition in Wikipedia? :)

**Comment by yoavweiss** [comment]
My problem with Wikipedia is that anyone can temporarily modify the definitions, which seems like something that can lead to trouble... I don't have a specific issue with the Wikipedia definitions (although I haven't looked too closely at them) if they were on "stable ground"

**Comment by marcoscaceres** [comment]
The question I think needs an answer here is: is the definition of "unix-time" and "clock drift" being used for implementation purposes, or is it just informative? 

If it's just informative, then citing wikipedia doesn't really matter (but maybe cite it properly, by adding it to SpecRef)... but if there is demonstrable implementation impact (i.e., some kind of normative requirement), then please do reference an actual spec.

**Comment by yoavweiss** [comment]
OK, so I think the use of "clock drift" is OK, as it's non-normative. #66 replaces "Unix time" with stricter ECMA-262 definitions
