### ISSUE TITLE
ReSpec errors

### ISSUE THREAD

**Issue by npm1** [w3c/hr-time#76]
Currently, https://w3c.github.io/hr-time/ contains 1 warning and 2 errors.

Warning is: "Linter (local-refs-exist): Broken local reference found in document. Please fix the links mentioned. See developer console. Occured at: 1, 2."

Errors are both: "Couldn't expand inline reference. The id "" is not in the document. at: 1."

But if I copy the html file and open it locally I see no warning or error.

**Comment by marcoscaceres** [comment]
Must be some caching issue (old version of ReSpec still cached or the references database became corrupted).    

Can't reproduce either, so closing.
