### ISSUE TITLE
Performance should be a partial interface?

### ISSUE THREAD

**Issue by foolip** [w3c/hr-time#8]
https://w3c.github.io/hr-time/#the-performance-interface

Like in https://github.com/w3c/performance-timeline/issues/32, there needs to be exactly one spec that defines the interface, and all others should have partial interfaces.

**Comment by igrigorik** [comment]
HR-time defines the interface, others extend it. I belive everything is already covered (modulo pending performance-timeline update)?

**Comment by foolip** [comment]
Closing this, as this spec is the intended new definition.
