### ISSUE TITLE
Time origin of event timestamps across iframes

### ISSUE THREAD

**Issue by querymetrics** [w3c/hr-time#81]
In the case that event listener functions are defined in another window from which the event is created, the time origin of high resolution event timestamps has implementation differences:

* Current behavior in Chrome, Firefox, Edge: The event `timeStamp` received in all listeners, regardless of which window the functions were defined in, uses the time origin of the window that the event was created in. Listeners in parent and child windows will receive the same value for `timeStamp`.

* Current behavior in Safari (desktop and iOS): The event `timeStamp` uses the time origin of the window that the listener function is defined in. Listeners in parent and child windows will receive a different value for `timeStamp`.

I'm not sure which implementation is the "correct" one.

The Boomerang RUM library is often loaded in an iframe and we add event listeners to the parent window to calculate things like time to first interaction, interaction delay, etc. It is hard for us to detect which time origin is being used.

I setup a repro page here: https://querymetrics.com/event-timestamp.html

**Comment by rniwa** [comment]
This is defined by the [DOM spec](https://dom.spec.whatwg.org/#dom-event-timestamp):
> The timeStamp attribute must return the value it was initialized to.

So each event listener should be receiving the same timestamp. Given that, I think this is just a bug in WebKit.

**Comment by toddreifsteck** [comment]
@rniwa Can you add a note to the Safari bug to double-check that a WPT test exists?

**Comment by rniwa** [comment]
Here's WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=200355

Here's WPT issue to add a test (for house keeping purposes): https://github.com/web-platform-tests/wpt/issues/18238
