### ISSUE TITLE
Make high resolution time dependant on cross-origin isolated

### ISSUE THREAD

**Issue by annevk** [w3c/hr-time#89]
With #88 solved, it would be good if the 5 microseconds resolution would be made conditional upon cross-origin isolated.

See https://github.com/whatwg/html/pull/4734. Though see https://github.com/whatwg/html/issues/5435 about potentially having to refer a slightly different concept.

**Comment by mikewest** [comment]
This sounds pretty reasonable to me.

**Comment by yoavweiss** [comment]
Should this be blocked on the definition of isolated contexts?

**Comment by npm1** [comment]
Chrome's current resolution is 5 microseconds for platforms other than Android. Does that mean we'll need to coarsen the timer more for these platforms? What would be the new maximum resolution for non-isolated?

**Comment by yoavweiss** [comment]
This was [discussed](https://docs.google.com/document/d/e/2PACX-1vSduIea0ImwkiVzFaD3ZmMv4YO-EGxw6kG-btBR4yeavTCO1lUoL1haM3yz6GAvj_b2Ya82PpezI0CF/pub) at a WebPerfWG call a couple of months back.

It was decided that once the underlying primitives are integrated into HTML (which I believe they now are), we'd estimate if this goes into L2 or L3 based on the changes themselves.

**Comment by yoavweiss** [comment]
I think the next step is for me to try and take a stab as defining something that outlines what browsers are currently doing, and what COEP/COOP would enable them to do.
