### ISSUE TITLE
Define the window.performance attribute

### ISSUE THREAD

**Issue by foolip** [w3c/hr-time#9]
This is currently in http://www.w3.org/TR/navigation-timing/#sec-window.performance-attribute and if High Resolution Time is destined to take over the main definition of the `Performance` API it would make sense to move this as well.

Bonus points for also defining it for workers, which Blink has but I can't find any spec for it.

**Comment by toddreifsteck** [comment]
Nice catch! Agreed.

**Comment by foolip** [comment]
If I could make a wish, it would also be that in the new spec it's just called "Extensions to the Window interface" like in other specs:
http://dev.w3.org/csswg/cssom/#extensions-to-the-window-interface
http://dev.w3.org/csswg/cssom-view/#extensions-to-the-window-interface

**Comment by foolip** [comment]
Now fixed: https://github.com/w3c/hr-time/issues/10#issuecomment-121661693
