### ISSUE TITLE
Export definition of DOMHighResTimeStamp

### ISSUE THREAD

**Issue by hober** [w3c/hr-time#90]
I tried to reference it from another spec by writing `{{DOMHighResTimeStamp}}` in Bikeshed, but autolinking failed.

**Comment by marcoscaceres** [comment]
Please make sure to republish the spec to /TR/ (looks like auto-publishing through TravisCI is not working, as the document on TR is still from 2019). The Shepherd database (the thing that contains all the exports) only picks them up from documents on /TR/.

**Comment by yoavweiss** [comment]
^^ @plehegar
