### ISSUE TITLE
Expose "unsafe now" for internal uses

### ISSUE THREAD

**Issue by yoavweiss** [w3c/hr-time#99]
As discussed in https://github.com/w3c/hr-time/issues/96#issuecomment-697271518, there are internal users that required access to unjittered raw monotonic timers. We should define and expose it for them.

**Comment by annevk** [comment]
I guess it would be good to as part of this try to more fully understand at least one of the use cases as other things might be needed as well, such as making an unsafe timestamp safe somehow.
